import ACCOUNTS_LOADED from './ACCOUNTS_LOADED'
import ACCOUNT_CREATE from './ACCOUNT_CREATE'
import ACCOUNT_DELETE from './ACCOUNT_DELETE'
import ACCOUNT_EDIT_NOTE from './ACCOUNT_EDIT_NOTE'
import ACCOUNT_EDIT_TRASH from './ACCOUNT_EDIT_TRASH'
import ACCOUNT_ICON_UPDATE from './ACCOUNT_ICON_UPDATE'
import FILES_LOADED from './FILES_LOADED'
import INITIAL_LOAD from './INITIAL_LOAD'
import MAIL_CONTENT_LOADED from './MAIL_CONTENT_LOADED'
import MAIL_DELETE from './MAIL_DELETE'
import MAIL_EDIT_ARCHIVED from './MAIL_EDIT_ARCHIVED'
import MAIL_EDIT_READ from './MAIL_EDIT_READ'
import MAIL_EDIT_TRASH from './MAIL_EDIT_TRASH'
import MAIL_INCOMING from './MAIL_INCOMING'
import MAIL_LOADED from './MAIL_LOADED'
import MAIL_REFRESHED from './MAIL_REFRESHED'
import SCREENSHOTS_LOADED from './SCREENSHOTS_LOADED'
import SCREENSHOT_DELETE from './SCREENSHOT_DELETE'
import SCREENSHOT_EDIT_FAVORITE from './SCREENSHOT_EDIT_FAVORITE'
import SCREENSHOT_EDIT_TRASH from './SCREENSHOT_EDIT_TRASH'
import SCREENSHOT_UPLOAD from './SCREENSHOT_UPLOAD'
import { Socket } from 'socket.io-client'
import USER_ADD_ADDRESS from './USER_ADD_ADDRESS'
import USER_AVATAR_UPDATE from './USER_AVATAR_UPDATE'
import USER_EDIT_ADDRESS_NAME from './USER_EDIT_ADDRESS_NAME'
import USER_ICON_DELETE from './USER_ICON_DELETE'
import USER_ICON_UPLOAD from './USER_ICON_UPLOAD'
import USER_REMOVE_ADDRESS from './USER_REMOVE_ADDRESS'
import USER_SET_STATUS from './USER_SET_STATUS'
import USER_UPDATE_ADDRESSES from './USER_UPDATE_ADDRESSES'

export default (socket: Socket): void => {
	ACCOUNTS_LOADED(socket)
	ACCOUNT_CREATE(socket)
	ACCOUNT_DELETE(socket)
	ACCOUNT_EDIT_NOTE(socket)
	ACCOUNT_EDIT_TRASH(socket)
	ACCOUNT_ICON_UPDATE(socket)
	FILES_LOADED(socket)
	INITIAL_LOAD(socket)
	MAIL_CONTENT_LOADED(socket)
	MAIL_DELETE(socket)
	MAIL_EDIT_ARCHIVED(socket)
	MAIL_EDIT_READ(socket)
	MAIL_EDIT_TRASH(socket)
	MAIL_INCOMING(socket)
	MAIL_LOADED(socket)
	MAIL_REFRESHED(socket)
	SCREENSHOTS_LOADED(socket)
	SCREENSHOT_DELETE(socket)
	SCREENSHOT_EDIT_FAVORITE(socket)
	SCREENSHOT_EDIT_TRASH(socket)
	SCREENSHOT_UPLOAD(socket)
	USER_ADD_ADDRESS(socket)
	USER_AVATAR_UPDATE(socket)
	USER_EDIT_ADDRESS_NAME(socket)
	USER_ICON_DELETE(socket)
	USER_ICON_UPLOAD(socket)
	USER_REMOVE_ADDRESS(socket)
	USER_SET_STATUS(socket)
	USER_UPDATE_ADDRESSES(socket)
}