import LOAD_ACCOUNTS from './LOAD_ACCOUNTS'
import LOAD_DATA from './LOAD_DATA'
import LOAD_FILES from './LOAD_FILES'
import LOAD_MAIL from './LOAD_MAIL'
import LOAD_MAIL_CONTENT from './LOAD_MAIL_CONTENT'
import LOAD_SCREENSHOTS from './LOAD_SCREENSHOTS'
import REFRESH_MAIL from './REFRESH_MAIL'
import USER_SET_STATUS from './USER_SET_STATUS'

export default [
	LOAD_ACCOUNTS,
	LOAD_DATA,
	LOAD_FILES,
	LOAD_MAIL,
	LOAD_MAIL_CONTENT,
	LOAD_SCREENSHOTS,
	REFRESH_MAIL,
	USER_SET_STATUS
]
